import Head from 'next/head'
import { Inter } from 'next/font/google'
import { FormEvent, useState } from 'react'
import { useContextAuth } from '../context/signContext';
import { GetServerSideProps } from 'next';
import { parseCookies } from 'nookies';


const inter = Inter({ subsets: ['latin'] })

export default function SignIn() {
  const [email, setEmail] = useState('')
  const [password, setpassword] = useState('')
  const { signInAuth, isAuthenticated } = useContextAuth();

  async function handleSubmit(event: FormEvent) {
    event.preventDefault()
    const data = {
      email,
      password,
    }
    await signInAuth(data)
  }

  return (
    <>
      <Head>
        <title>NextAuth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div>
          <form onSubmit={handleSubmit}>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
            <input type="password" value={password} onChange={(e) => setpassword(e.target.value)} />
            <button type='submit'>Entar</button>
          </form>
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = parseCookies(ctx)
  if (cookies['nextAuth.token']) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false
      }
    }

  }

  return {
    props: {}
  }

}
